#!/bin/bash

#LD_LIBRARY_PATH=././usr/lib/x86_64-linux-gnu/
#export LD_LIBRARY_PATH

#EXECPATH=././usr/bin/xfreerdp


HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH=${HERE}/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
exec "${HERE}/usr/bin/xfreerdp" "$@"
